SRC_TRG_TXT_DIC = {
    # Human face
    "tanned": (["face"], ["tanned face"]),
    "pale": (["face"], ["pale face"]),
    "makeup": (["person"], ["person with makeup"]),
    "no_makeup": (["person"], ["person without makeup"]),
    "old": (["person"], ["old person"]),
    "young": (["person"], ["young person"]),
    "beards": (["person"], ["person with beards"]),
    "angry": (["face"], ["angry face"]),
    "surprised": (["face"], ["surprised face"]),
    "smiling": (["face"], ["smiling face"]),
    "blond_hair": (["person"], ["person with blond hair"]),
    "red_hair": (["person"], ["person with red hair"]),
    "grey_hair": (["person"], ["person with red hair"]),
    "curly_hair": (["person"], ["person with curly hair"]),
    "nicolas": (["Person"], ["Nicolas Cage"]),
    "zuckerberg": (["Person"], ["Mark Zuckerberg"]),
    "benedict": (["Person"], ["Benedict Cumberbatch"]),
    "gogh": (["photo"], ["painting by Gogh"]),
    "frida": (["photo"], ["self-portrait by Frida Kahlo"]),
    "modigliani": (["photo"], ["Painting in Modigliani style"]),
    "sketch": (["photo"], ["sketch"]),
    "watercolor": (["photo"], ["Watercolor Art with Thick Brushstrokes"]),
    "elf": (["Human"], ["Tolkien elf"]),
    "super_saiyan": (["Human"], ["Super saiyan"]),
    "pixar": (["Human"], ["3D render in the style of Pixar"]),
    "neanderthal": (["Human"], ["Neanderthal"]),
    "zombie": (["Human"], ["Zombie"]),
    "jocker": (["Human"], ["The Jocker"]),
    # Dog face
    "dog_nicolas": (["Dog"], ["Nicolas Cage"]),
    "dog_yorkshire": (["Dog"], ["Yorkshire Terrier"]),
    "dog_smiling": (["Dog"], ["Smiling Dog"]),
    "dog_zombie": (["Dog"], ["Zombie"]),
    "dog_super_saiyan": (["Dog"], ["Super saiyan"]),
    "dog_venom": (["Dog"], ["Venom"]),
    "dog_bear": (["Dog"], ["Bear"]),
    "dog_fox": (["Dog"], ["Fox"]),
    "dog_wolf": (["Dog"], ["Wolf"]),
    "dog_hamster": (["Dog"], ["Hamster"]),
    # Church
    "church_snow": (["Church"], ["Snow Coverd Church"]),
    "church_night": (["Church"], ["Church at night"]),
    "church_red_brick": (["Church"], ["Red brick wall Church"]),
    "church_golden": (["Church"], ["Golden Church"]),
    "church_wooden_house": (["Church"], ["Wooden House"]),
    "church_gothic": (["Church"], ["Gothic Church"]),
    "church_ancient_tower": (["Church"], ["Ancient traditional Asian tower"]),
    "church_temple": (["Church"], ["Temple"]),
    "church_factory": (["church"], ["factory with chimneys"]),
    "church_department_store": (["church"], ["department store"]),
    # Bedroom
    "bedroom_blue": (["Bedroom"], ["Blue tone Bedroom"]),
    "bedroom_green": (["Bedroom"], ["Green tone Bedroom"]),
    "bedroom_golden": (["Bedroom"], ["Golden Bedroom"]),
    "bedroom_princess": (["Bedroom"], ["Princess Bedroom"]),
    "bedroom_palace": (["Bedroom"], ["Palace Bedroom"]),
    "bedroom_wooden": (["Bedroom"], ["Wooden Bedroom"]),
    
    # GEODE / TESTING
    # "house_in_Africa": (["house"], ["A house in Africa."]),  # copy
    # "spice_in_Africa":(["spice"], ["A spice in Africa."]),
    # "religous_building_in_Africa": (["religious building"], ["A religious building in Africa."]),
    # "medicine_in_Africa":(["medicine"], ["medicine in Africa."]),
    # "dustbin_in_Africa": (["A dustbin."], ["A dustbin in Africa."]),
    # "hand_soap_in_Africa": (["hand soap."], ["hand soap in Africa."]),

    "house_in_Africa": (["house"], ["A house in Africa"]),
    "house_in_Americas": (["house"], ["A house in Americas"]),
    "house_in_EastAsia": (["house"], ["A house in East Asia"]),
    "house_in_Europe": (["house"], ["A house in Europe"]),
    "house_in_SouthEastAsia": (["house"], ["A house in Southeast Asia"]),
    "house_in_WestAsia": (["house"], ["A house in West Asia"]),
    "spices_in_Africa": (["spices"], ["A spices in Africa"]),
    "spices_in_Americas": (["spices"], ["A spices in Americas"]),
    "spices_in_EastAsia": (["spices"], ["A spices in East Asia"]),
    "spices_in_Europe": (["spices"], ["A spices in Europe"]),
    "spices_in_SouthEastAsia": (["spices"], ["A spices in Southeast Asia"]),
    "spices_in_WestAsia": (["spices"], ["A spices in West Asia"]),
    "religious_building_in_Africa": (["religious_building"], ["A religious_building in Africa"]),
    "religious_building_in_Americas": (["religious_building"], ["A religious_building in Americas"]),
    "religious_building_in_EastAsia": (["religious_building"], ["A religious_building in East Asia"]),
    "religious_building_in_Europe": (["religious_building"], ["A religious_building in Europe"]),
    "religious_building_in_SouthEastAsia": (["religious_building"], ["A religious_building in Southeast Asia"]),
    "religious_building_in_WestAsia": (["religious_building"], ["A religious_building in West Asia"]),
    "hand_soap_in_Africa": (["hand_soap"], ["A hand_soap in Africa"]),
    "hand_soap_in_Americas": (["hand_soap"], ["A hand_soap in Americas"]),
    "hand_soap_in_EastAsia": (["hand_soap"], ["A hand_soap in East Asia"]),
    "hand_soap_in_Europe": (["hand_soap"], ["A hand_soap in Europe"]),
    "hand_soap_in_SouthEastAsia": (["hand_soap"], ["A hand_soap in Southeast Asia"]),
    "hand_soap_in_WestAsia": (["hand_soap"], ["A hand_soap in West Asia"]),
    "dustbin_in_Africa": (["dustbin"], ["A dustbin in Africa"]),
    "dustbin_in_Americas": (["dustbin"], ["A dustbin in Americas"]),
    "dustbin_in_EastAsia": (["dustbin"], ["A dustbin in East Asia"]),
    "dustbin_in_Europe": (["dustbin"], ["A dustbin in Europe"]),
    "dustbin_in_SouthEastAsia": (["dustbin"], ["A dustbin in Southeast Asia"]),
    "dustbin_in_WestAsia": (["dustbin"], ["A dustbin in West Asia"]),
    "medicine_in_Africa": (["medicine"], ["A medicine in Africa"]),
    "medicine_in_Americas": (["medicine"], ["A medicine in Americas"]),
    "medicine_in_EastAsia": (["medicine"], ["A medicine in East Asia"]),
    "medicine_in_Europe": (["medicine"], ["A medicine in Europe"]),
    "medicine_in_SouthEastAsia": (["medicine"], ["A medicine in Southeast Asia"]),
    "medicine_in_WestAsia": (["medicine"], ["A medicine in West Asia"]),
}
